#!/bin/bash
mkdir my_first_directory /tmp/#!/bin/bash
mkdir my_first_directory /tmp/#!/bin/bash
mkdir my_first_directory /tmp/#!/bin/bash
mkdir my_first_directory /tmp/#!/bin/bash
mkdir my_first_directory /tmp/#!/bin/bash
mkdir my_first_directory /tmp/#!/bin/bash
mkdir my_first_directory /tmp/#!/bin/bash
mkdir my_first_directory /tmp/#!/bin/bash
mkdir my_first_directory /tmp/
